### ISSUE TITLE
Make intermediate entity classes public

### ISSUE THREAD

**Issue by markus-s24** [BingAds/BingAds-Java-SDK#49]
Intermediate entity classes that are "package private" (like BulkEntityNegativeKeyword) have some downsides:
   * instanceof does not work, so generic behaviour has to be implemented for each subclass.
   * Lambdas do not work (they compile, but lead to runtime errors), e.g. BulkAdGroupNegativeKeyword::getNegativeKeyword

My suggestion: Make the classes public and instead make their constructors protected (or package private).

**Comment by eric-urban** [comment]
@markus-s24 I apologize for the delayed reply. We are now actively investigating this request.

**Comment by eric-urban** [comment]
@markus-s24 thanks for the suggestion! Given low demand for these as public classes the team decided to keep them private for the time being. There is also concern that clients might mistakenly attempt to upload them directly although by design we only allow upload/download of public BulkEntity classes.
